// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hotel-service.proto

package hotel

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hotel struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City                 string               `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country              string               `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Phone                string               `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Description          string               `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Lat                  int32                `protobuf:"zigzag32,7,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 int32                `protobuf:"zigzag32,8,opt,name=long,proto3" json:"long,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Hotel) Reset()         { *m = Hotel{} }
func (m *Hotel) String() string { return proto.CompactTextString(m) }
func (*Hotel) ProtoMessage()    {}
func (*Hotel) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b50d6e00d7f62fc, []int{0}
}

func (m *Hotel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hotel.Unmarshal(m, b)
}
func (m *Hotel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hotel.Marshal(b, m, deterministic)
}
func (m *Hotel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hotel.Merge(m, src)
}
func (m *Hotel) XXX_Size() int {
	return xxx_messageInfo_Hotel.Size(m)
}
func (m *Hotel) XXX_DiscardUnknown() {
	xxx_messageInfo_Hotel.DiscardUnknown(m)
}

var xxx_messageInfo_Hotel proto.InternalMessageInfo

func (m *Hotel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Hotel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hotel) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Hotel) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Hotel) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Hotel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Hotel) GetLat() int32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Hotel) GetLong() int32 {
	if m != nil {
		return m.Long
	}
	return 0
}

func (m *Hotel) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Hotel) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Hotel                *Hotel   `protobuf:"bytes,2,opt,name=hotel,proto3" json:"hotel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b50d6e00d7f62fc, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetHotel() *Hotel {
	if m != nil {
		return m.Hotel
	}
	return nil
}

type CreateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b50d6e00d7f62fc, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Hotel)(nil), "v1.Hotel")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
}

func init() { proto.RegisterFile("hotel-service.proto", fileDescriptor_7b50d6e00d7f62fc) }

var fileDescriptor_7b50d6e00d7f62fc = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x6a, 0xe3, 0x30,
	0x14, 0x86, 0xb1, 0x13, 0x27, 0x63, 0x65, 0x26, 0x24, 0x9a, 0x19, 0x10, 0x9e, 0x81, 0x18, 0xaf,
	0xcc, 0xc0, 0xd8, 0xc4, 0xb3, 0x19, 0xba, 0x6b, 0xba, 0xe9, 0xa2, 0x2b, 0xb7, 0xab, 0xd2, 0x8d,
	0x62, 0xab, 0x89, 0xc0, 0x91, 0x54, 0x5b, 0x36, 0x64, 0xdb, 0x2b, 0xf4, 0x18, 0x3d, 0x4e, 0xaf,
	0xd0, 0x83, 0x14, 0x3d, 0xc5, 0x6d, 0x0a, 0x85, 0xee, 0x9e, 0x3e, 0xbd, 0xf7, 0xeb, 0xd7, 0xff,
	0xd0, 0xf7, 0xad, 0xd4, 0xac, 0xfa, 0xdb, 0xb0, 0xba, 0xe3, 0x05, 0x4b, 0x54, 0x2d, 0xb5, 0xc4,
	0x6e, 0xb7, 0x0c, 0x16, 0x1b, 0x29, 0x37, 0x15, 0x4b, 0x81, 0xac, 0xdb, 0xdb, 0x54, 0xf3, 0x1d,
	0x6b, 0x34, 0xdd, 0x29, 0xdb, 0x14, 0xfc, 0x3e, 0x34, 0x50, 0xc5, 0x53, 0x2a, 0x84, 0xd4, 0x54,
	0x73, 0x29, 0x1a, 0x7b, 0x1b, 0x3d, 0xba, 0xc8, 0x3b, 0x37, 0xd2, 0x78, 0x8a, 0x5c, 0x5e, 0x12,
	0x27, 0x74, 0xe2, 0x41, 0xee, 0xf2, 0x12, 0x63, 0x34, 0x14, 0x74, 0xc7, 0x88, 0x1b, 0x3a, 0xb1,
	0x9f, 0x43, 0x6d, 0x58, 0xc1, 0xf5, 0x9e, 0x0c, 0x2c, 0x33, 0x35, 0x26, 0x68, 0x5c, 0xc8, 0x56,
	0xe8, 0x7a, 0x4f, 0x86, 0x80, 0xfb, 0x23, 0xfe, 0x81, 0x3c, 0xb5, 0x95, 0x82, 0x11, 0x0f, 0xb8,
	0x3d, 0xe0, 0x10, 0x4d, 0x4a, 0xd6, 0x14, 0x35, 0x57, 0xc6, 0x07, 0x19, 0xc1, 0xdd, 0x31, 0xc2,
	0x33, 0x34, 0xa8, 0xa8, 0x26, 0xe3, 0xd0, 0x89, 0xe7, 0xb9, 0x29, 0xcd, 0xbb, 0x95, 0x14, 0x1b,
	0xf2, 0x05, 0x10, 0xd4, 0xf8, 0x3f, 0xf2, 0x8b, 0x9a, 0x51, 0xcd, 0xca, 0x53, 0x4d, 0xfc, 0xd0,
	0x89, 0x27, 0x59, 0x90, 0xd8, 0xbf, 0x26, 0x7d, 0x18, 0xc9, 0x55, 0x1f, 0x46, 0xfe, 0xd6, 0x6c,
	0x26, 0x5b, 0x55, 0x1e, 0x26, 0xd1, 0xe7, 0x93, 0xaf, 0xcd, 0xd1, 0x0a, 0x7d, 0x3b, 0x03, 0x99,
	0x9c, 0xdd, 0xb5, 0xac, 0xd1, 0xc6, 0x2a, 0x55, 0x1c, 0x52, 0xf3, 0x73, 0x53, 0xe2, 0x05, 0xf2,
	0x60, 0x55, 0x90, 0xdb, 0x24, 0xf3, 0x93, 0x6e, 0x99, 0x40, 0xc0, 0xb9, 0xe5, 0x51, 0x86, 0xa6,
	0xbd, 0x46, 0xa3, 0xa4, 0x68, 0xd8, 0x07, 0x22, 0x76, 0x17, 0x6e, 0xbf, 0x8b, 0xec, 0x06, 0x7d,
	0x05, 0x8d, 0x4b, 0xbb, 0x7e, 0x7c, 0x81, 0x46, 0x56, 0x03, 0xcf, 0x8d, 0xfe, 0x3b, 0x4f, 0x01,
	0x3e, 0x46, 0xf6, 0x89, 0xe8, 0xd7, 0xfd, 0xd3, 0xf3, 0x83, 0xfb, 0x33, 0x9a, 0xa5, 0xdd, 0x32,
	0x05, 0x1f, 0xa9, 0xcd, 0xe3, 0xc4, 0xf9, 0xb3, 0x1a, 0x5f, 0x5b, 0x6b, 0xeb, 0x11, 0xfc, 0xfe,
	0xdf, 0x4b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0xd4, 0x17, 0x93, 0x6d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HotelServiceClient is the client API for HotelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HotelServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type hotelServiceClient struct {
	cc *grpc.ClientConn
}

func NewHotelServiceClient(cc *grpc.ClientConn) HotelServiceClient {
	return &hotelServiceClient{cc}
}

func (c *hotelServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/v1.HotelService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotelServiceServer is the server API for HotelService service.
type HotelServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

// UnimplementedHotelServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHotelServiceServer struct {
}

func (*UnimplementedHotelServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterHotelServiceServer(s *grpc.Server, srv HotelServiceServer) {
	s.RegisterService(&_HotelService_serviceDesc, srv)
}

func _HotelService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.HotelService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HotelService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.HotelService",
	HandlerType: (*HotelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _HotelService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hotel-service.proto",
}
