<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hotel-service.proto

namespace GPBMetadata;

class HotelService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad1020a13686f74656c2d736572766963652e70726f746f12027631227f" .
            "0a05486f74656c120a0a026964180120012803120c0a046e616d65180220" .
            "012809120c0a0463697479180320012809120f0a07636f756e7472791804" .
            "20012809120d0a0570686f6e6518052001280912130a0b64657363726970" .
            "74696f6e180620012809120b0a036c6174180720012811120c0a046c6f6e" .
            "6718082001281122360a0d43726561746552657175657374120b0a036170" .
            "6918012001280912180a05686f74656c18022001280b32092e76312e486f" .
            "74656c22290a0e437265617465526573706f6e7365120b0a036170691801" .
            "20012809120a0a02696418022001280332410a0c486f74656c5365727669" .
            "636512310a0643726561746512112e76312e437265617465526571756573" .
            "741a122e76312e437265617465526573706f6e7365220042075a05686f74" .
            "656c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

