<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hotel-service.proto

namespace V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>v1.CreateRequest</code>
 */
class CreateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string api = 1;</code>
     */
    private $api = '';
    /**
     * <code>.v1.Hotel hotel = 2;</code>
     */
    private $hotel = null;

    public function __construct() {
        \GPBMetadata\HotelService::initOnce();
        parent::__construct();
    }

    /**
     * <code>string api = 1;</code>
     */
    public function getApi()
    {
        return $this->api;
    }

    /**
     * <code>string api = 1;</code>
     */
    public function setApi($var)
    {
        GPBUtil::checkString($var, True);
        $this->api = $var;
    }

    /**
     * <code>.v1.Hotel hotel = 2;</code>
     */
    public function getHotel()
    {
        return $this->hotel;
    }

    /**
     * <code>.v1.Hotel hotel = 2;</code>
     */
    public function setHotel(&$var)
    {
        GPBUtil::checkMessage($var, \V1\Hotel::class);
        $this->hotel = $var;
    }

}

