<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hotel-service.proto

namespace V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>v1.Hotel</code>
 */
class Hotel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string city = 3;</code>
     */
    private $city = '';
    /**
     * Generated from protobuf field <code>string country = 4;</code>
     */
    private $country = '';
    /**
     * Generated from protobuf field <code>string phone = 5;</code>
     */
    private $phone = '';
    /**
     * Generated from protobuf field <code>string description = 6;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>sint32 lat = 7;</code>
     */
    private $lat = 0;
    /**
     * Generated from protobuf field <code>sint32 long = 8;</code>
     */
    private $long = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp createdAt = 9;</code>
     */
    private $createdAt = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updatedAt = 10;</code>
     */
    private $updatedAt = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $name
     *     @type string $city
     *     @type string $country
     *     @type string $phone
     *     @type string $description
     *     @type int $lat
     *     @type int $long
     *     @type \Google\Protobuf\Timestamp $createdAt
     *     @type \Google\Protobuf\Timestamp $updatedAt
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\HotelService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city = 3;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country = 4;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Generated from protobuf field <code>string country = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 5;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 6;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 lat = 7;</code>
     * @return int
     */
    public function getLat()
    {
        return $this->lat;
    }

    /**
     * Generated from protobuf field <code>sint32 lat = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setLat($var)
    {
        GPBUtil::checkInt32($var);
        $this->lat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 long = 8;</code>
     * @return int
     */
    public function getLong()
    {
        return $this->long;
    }

    /**
     * Generated from protobuf field <code>sint32 long = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setLong($var)
    {
        GPBUtil::checkInt32($var);
        $this->long = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp createdAt = 9;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp createdAt = 9;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->createdAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updatedAt = 10;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updatedAt = 10;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updatedAt = $var;

        return $this;
    }

}

